version: '3.8'

services:
  election-web-app:
    container_name: election-web-app
    image: klydem/election-web-app:latest
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - db
      - migration-side-car
    networks:
      - web-app-network
    restart: unless-stopped

  migration-side-car:
    container_name: db-migration-side-car
    image: klydem/election-web-app:latest
    command: /bin/bash -c "rails db:create && rails db:migrate && echo 'Success' && exit 0"
    env_file: .env
    depends_on:
      - db
    networks:
      - web-app-network

networks:
  web-app-network:
    driver: bridge
