
# generated by: jx gitops variables
export APP_NAME='election-web-app'
export BRANCH_NAME='main'
export BUILD_NUMBER='108'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export DOCKER_REGISTRY_ORG='surreyfyp'
export DOMAIN='35.178.110.181.nip.io'
export GIT_BRANCH='main'
export JENKINS_X_URL='http://dashboard-jx.35.178.110.181.nip.io/surreyfyp/election-web-app/main/108'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='847399026905.dkr.ecr.eu-west-2.amazonaws.com/surreyfyp/election-web-app:0.0.102'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export REPO_NAME='election-web-app'
export REPO_OWNER='surreyfyp'
export VERSION='0.0.102'


# content from git...

# generated by: jx gitops variables
export APP_NAME='election-web-app'
export BRANCH_NAME='main'
export BUILD_NUMBER='107'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export DOCKER_REGISTRY_ORG='surreyfyp'
export DOMAIN='35.178.110.181.nip.io'
export GIT_BRANCH='main'
export JENKINS_X_URL='http://dashboard-jx.35.178.110.181.nip.io/surreyfyp/election-web-app/main/107'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='847399026905.dkr.ecr.eu-west-2.amazonaws.com/surreyfyp/election-web-app:0.0.101'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export REPO_NAME='election-web-app'
export REPO_OWNER='surreyfyp'
export VERSION='0.0.101'


# content from git...

# generated by: jx gitops variables
export APP_NAME='election-web-app'
export BRANCH_NAME='main'
export BUILD_NUMBER='106'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export DOCKER_REGISTRY_ORG='surreyfyp'
export DOMAIN='35.178.110.181.nip.io'
export GIT_BRANCH='main'
export JENKINS_X_URL='http://dashboard-jx.35.178.110.181.nip.io/surreyfyp/election-web-app/main/106'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='847399026905.dkr.ecr.eu-west-2.amazonaws.com/surreyfyp/election-web-app:0.0.100'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export REPO_NAME='election-web-app'
export REPO_OWNER='surreyfyp'
export VERSION='0.0.100'


# content from git...

# generated by: jx gitops variables
export APP_NAME='election-web-app'
export BRANCH_NAME='main'
export BUILD_NUMBER='96'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export DOCKER_REGISTRY_ORG='surreyfyp'
export DOMAIN='35.178.110.181.nip.io'
export GIT_BRANCH='main'
export JENKINS_X_URL='http://dashboard-jx.35.178.110.181.nip.io/surreyfyp/election-web-app/main/96'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='847399026905.dkr.ecr.eu-west-2.amazonaws.com/surreyfyp/election-web-app:0.0.90'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export REPO_NAME='election-web-app'
export REPO_OWNER='surreyfyp'
export VERSION='0.0.90'


# content from git...

# generated by: jx gitops variables
export APP_NAME='election-web-app'
export BRANCH_NAME='main'
export BUILD_NUMBER='94'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export DOCKER_REGISTRY_ORG='surreyfyp'
export DOMAIN='35.178.110.181.nip.io'
export GIT_BRANCH='main'
export JENKINS_X_URL='http://dashboard-jx.35.178.110.181.nip.io/surreyfyp/election-web-app/main/94'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='847399026905.dkr.ecr.eu-west-2.amazonaws.com/surreyfyp/election-web-app:0.0.89'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export REPO_NAME='election-web-app'
export REPO_OWNER='surreyfyp'
export VERSION='0.0.89'


# content from git...

# generated by: jx gitops variables
export APP_NAME='election-web-app'
export BRANCH_NAME='main'
export BUILD_NUMBER='92'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export DOCKER_REGISTRY_ORG='surreyfyp'
export DOMAIN='35.178.110.181.nip.io'
export GIT_BRANCH='main'
export JENKINS_X_URL='http://dashboard-jx.35.178.110.181.nip.io/surreyfyp/election-web-app/main/92'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='847399026905.dkr.ecr.eu-west-2.amazonaws.com/surreyfyp/election-web-app:0.0.87'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export REPO_NAME='election-web-app'
export REPO_OWNER='surreyfyp'
export VERSION='0.0.87'


# content from git...

# generated by: jx gitops variables
export APP_NAME='election-web-app'
export BRANCH_NAME='main'
export BUILD_NUMBER='87'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export DOCKER_REGISTRY_ORG='surreyfyp'
export DOMAIN='35.178.110.181.nip.io'
export GIT_BRANCH='main'
export JENKINS_X_URL='http://dashboard-jx.35.178.110.181.nip.io/surreyfyp/election-web-app/main/87'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='847399026905.dkr.ecr.eu-west-2.amazonaws.com/surreyfyp/election-web-app:0.0.83'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export REPO_NAME='election-web-app'
export REPO_OWNER='surreyfyp'
export VERSION='0.0.83'


# content from git...

# generated by: jx gitops variables
export APP_NAME='election-web-app'
export BRANCH_NAME='main'
export BUILD_NUMBER='85'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export DOCKER_REGISTRY_ORG='surreyfyp'
export DOMAIN='35.178.110.181.nip.io'
export GIT_BRANCH='main'
export JENKINS_X_URL='http://dashboard-jx.35.178.110.181.nip.io/surreyfyp/election-web-app/main/85'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='847399026905.dkr.ecr.eu-west-2.amazonaws.com/surreyfyp/election-web-app:0.0.81'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export REPO_NAME='election-web-app'
export REPO_OWNER='surreyfyp'
export VERSION='0.0.81'


# content from git...

# generated by: jx gitops variables
export APP_NAME='election-web-app'
export BRANCH_NAME='main'
export BUILD_NUMBER='84'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export DOCKER_REGISTRY_ORG='surreyfyp'
export DOMAIN='35.178.110.181.nip.io'
export GIT_BRANCH='main'
export JENKINS_X_URL='http://dashboard-jx.35.178.110.181.nip.io/surreyfyp/election-web-app/main/84'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='847399026905.dkr.ecr.eu-west-2.amazonaws.com/surreyfyp/election-web-app:0.0.80'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export REPO_NAME='election-web-app'
export REPO_OWNER='surreyfyp'
export VERSION='0.0.80'


# content from git...

# generated by: jx gitops variables
export APP_NAME='election-web-app'
export BRANCH_NAME='main'
export BUILD_NUMBER='83'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export DOCKER_REGISTRY_ORG='surreyfyp'
export DOMAIN='35.178.110.181.nip.io'
export GIT_BRANCH='main'
export JENKINS_X_URL='http://dashboard-jx.35.178.110.181.nip.io/surreyfyp/election-web-app/main/83'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='847399026905.dkr.ecr.eu-west-2.amazonaws.com/surreyfyp/election-web-app:0.0.79'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export REPO_NAME='election-web-app'
export REPO_OWNER='surreyfyp'
export VERSION='0.0.79'


# content from git...

# generated by: jx gitops variables
export APP_NAME='election-web-app'
export BRANCH_NAME='main'
export BUILD_NUMBER='82'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export DOCKER_REGISTRY_ORG='surreyfyp'
export DOMAIN='35.178.110.181.nip.io'
export GIT_BRANCH='main'
export JENKINS_X_URL='http://dashboard-jx.35.178.110.181.nip.io/surreyfyp/election-web-app/main/82'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='847399026905.dkr.ecr.eu-west-2.amazonaws.com/surreyfyp/election-web-app:0.0.78'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export REPO_NAME='election-web-app'
export REPO_OWNER='surreyfyp'
export VERSION='0.0.78'


# content from git...

# generated by: jx gitops variables
export APP_NAME='election-web-app'
export BRANCH_NAME='main'
export BUILD_NUMBER='79'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export DOCKER_REGISTRY_ORG='surreyfyp'
export DOMAIN='35.178.110.181.nip.io'
export GIT_BRANCH='main'
export JENKINS_X_URL='http://dashboard-jx.35.178.110.181.nip.io/surreyfyp/election-web-app/main/79'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='847399026905.dkr.ecr.eu-west-2.amazonaws.com/surreyfyp/election-web-app:0.0.77'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export REPO_NAME='election-web-app'
export REPO_OWNER='surreyfyp'
export VERSION='0.0.77'


# content from git...

# generated by: jx gitops variables
export APP_NAME='election-web-app'
export BRANCH_NAME='main'
export BUILD_NUMBER='78'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export DOCKER_REGISTRY_ORG='surreyfyp'
export DOMAIN='35.178.110.181.nip.io'
export GIT_BRANCH='main'
export JENKINS_X_URL='http://dashboard-jx.35.178.110.181.nip.io/surreyfyp/election-web-app/main/78'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='847399026905.dkr.ecr.eu-west-2.amazonaws.com/surreyfyp/election-web-app:0.0.76'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export REPO_NAME='election-web-app'
export REPO_OWNER='surreyfyp'
export VERSION='0.0.76'


# content from git...

# generated by: jx gitops variables
export APP_NAME='election-web-app'
export BRANCH_NAME='main'
export BUILD_NUMBER='76'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export DOCKER_REGISTRY_ORG='surreyfyp'
export DOMAIN='35.178.110.181.nip.io'
export GIT_BRANCH='main'
export JENKINS_X_URL='http://dashboard-jx.35.178.110.181.nip.io/surreyfyp/election-web-app/main/76'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='847399026905.dkr.ecr.eu-west-2.amazonaws.com/surreyfyp/election-web-app:0.0.74'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export REPO_NAME='election-web-app'
export REPO_OWNER='surreyfyp'
export VERSION='0.0.74'


# content from git...

# generated by: jx gitops variables
export APP_NAME='election-web-app'
export BRANCH_NAME='main'
export BUILD_NUMBER='75'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export DOCKER_REGISTRY_ORG='surreyfyp'
export DOMAIN='35.178.110.181.nip.io'
export GIT_BRANCH='main'
export JENKINS_X_URL='http://dashboard-jx.35.178.110.181.nip.io/surreyfyp/election-web-app/main/75'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='847399026905.dkr.ecr.eu-west-2.amazonaws.com/surreyfyp/election-web-app:0.0.73'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='847399026905.dkr.ecr.eu-west-2.amazonaws.com'
export REPO_NAME='election-web-app'
export REPO_OWNER='surreyfyp'
export VERSION='0.0.73'




























