require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ballots", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Ballot. As you add validations to Ballot, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Ballot.create! valid_attributes
      get ballots_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ballot = Ballot.create! valid_attributes
      get ballot_url(ballot)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ballot_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      ballot = Ballot.create! valid_attributes
      get edit_ballot_url(ballot)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Ballot" do
        expect {
          post ballots_url, params: { ballot: valid_attributes }
        }.to change(Ballot, :count).by(1)
      end

      it "redirects to the created ballot" do
        post ballots_url, params: { ballot: valid_attributes }
        expect(response).to redirect_to(ballot_url(Ballot.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Ballot" do
        expect {
          post ballots_url, params: { ballot: invalid_attributes }
        }.to change(Ballot, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post ballots_url, params: { ballot: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ballot" do
        ballot = Ballot.create! valid_attributes
        patch ballot_url(ballot), params: { ballot: new_attributes }
        ballot.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ballot" do
        ballot = Ballot.create! valid_attributes
        patch ballot_url(ballot), params: { ballot: new_attributes }
        ballot.reload
        expect(response).to redirect_to(ballot_url(ballot))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        ballot = Ballot.create! valid_attributes
        patch ballot_url(ballot), params: { ballot: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ballot" do
      ballot = Ballot.create! valid_attributes
      expect {
        delete ballot_url(ballot)
      }.to change(Ballot, :count).by(-1)
    end

    it "redirects to the ballots list" do
      ballot = Ballot.create! valid_attributes
      delete ballot_url(ballot)
      expect(response).to redirect_to(ballots_url)
    end
  end
end
