require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/stored_voters", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # StoredVoter. As you add validations to StoredVoter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      StoredVoter.create! valid_attributes
      get stored_voters_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      stored_voter = StoredVoter.create! valid_attributes
      get stored_voter_url(stored_voter)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_stored_voter_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      stored_voter = StoredVoter.create! valid_attributes
      get edit_stored_voter_url(stored_voter)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StoredVoter" do
        expect {
          post stored_voters_url, params: { stored_voter: valid_attributes }
        }.to change(StoredVoter, :count).by(1)
      end

      it "redirects to the created stored_voter" do
        post stored_voters_url, params: { stored_voter: valid_attributes }
        expect(response).to redirect_to(stored_voter_url(StoredVoter.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StoredVoter" do
        expect {
          post stored_voters_url, params: { stored_voter: invalid_attributes }
        }.to change(StoredVoter, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post stored_voters_url, params: { stored_voter: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested stored_voter" do
        stored_voter = StoredVoter.create! valid_attributes
        patch stored_voter_url(stored_voter), params: { stored_voter: new_attributes }
        stored_voter.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the stored_voter" do
        stored_voter = StoredVoter.create! valid_attributes
        patch stored_voter_url(stored_voter), params: { stored_voter: new_attributes }
        stored_voter.reload
        expect(response).to redirect_to(stored_voter_url(stored_voter))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        stored_voter = StoredVoter.create! valid_attributes
        patch stored_voter_url(stored_voter), params: { stored_voter: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested stored_voter" do
      stored_voter = StoredVoter.create! valid_attributes
      expect {
        delete stored_voter_url(stored_voter)
      }.to change(StoredVoter, :count).by(-1)
    end

    it "redirects to the stored_voters list" do
      stored_voter = StoredVoter.create! valid_attributes
      delete stored_voter_url(stored_voter)
      expect(response).to redirect_to(stored_voters_url)
    end
  end
end
