# Database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.credentials.db_name %>
  username: <%= Rails.application.credentials.db_username %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> # For details on connection pooling, see Rails configuration guide https://guides.rubyonrails.org/configuring.html#database-pooling

# All Pull Requests use this database
preview:  
  <<: *default
  host: <%= Rails.application.credentials.staging_db_host %> 
  password: <%= Rails.application.credentials.staging_db_secret %> 

# JX-Staging and JX-Production use this database
production: 
  <<: *default
  host: <%= Rails.application.credentials.production_db_host %> 
  password: <%= Rails.application.credentials.production_db_secret %> 
  pool: 5


test: # Pretty sure some rspec tests may use this
  <<: *default
  adapter: postgresql
  encoding: utf8
  host: <%= Rails.application.credentials.staging_db_host %> 
  password: <%= Rails.application.credentials.staging_db_secret %> 

ltest:  # Local Tests
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  host: localhost
  username: myapp
  password: password1

development: # Pretty sure some rspec tests may use this
  <<: *default
  host: <%= Rails.application.credentials.staging_db_host %> 
  password: <%= Rails.application.credentials.staging_db_secret %> 

