apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: task-code-scanning
spec:
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    name: ""
    resources: {}
  steps:
  - image: ruby:3.0.3
    name: code-scanning-ruby-lint # to improve these Code Scanning steps should be in parallel
    # workingDir: /workspace/source
    resources: {}
    script: |
      #!/bin/bash

      set -e # Makes terminal exit on error
      apt update
      apt install nodejs -y
      node -v
      apt install npm -y

      # For Prettier - ESLint - stylelint
      npm install --save-dev prettier-eslint
      npm install --save-dev prettier-eslint-cli
      npm install prettier-stylelint --save-dev

      # Standrd Ruby on Rails bundle install
      bundle install

      echo "-------- RUBOCOP | START --------"
      cd ./bin
      chmod u+r+x error_handler.sh
      ./error_handler.sh "rubocop --parallel"; cd ..
      echo "-------- RUBOCOP | END --------"
      
      echo "-------- Prettier - ESLint - stylelint | START --------"
      cd ./bin 
      ./error_handler.sh "npm run fix-code"
      ./error_handler.sh "npm run fix-styles"
      cd ..
      echo "-------- Prettier - ESLint - stylelint | END --------"
  - image: ruby:3.0.3
    name: code-scanning-ruby-security-checks # Brakeman security test
    resources: {}
    script: |
      #!/bin/bash
      set -e
      gem install brakeman
      brakeman -aq
  workspaces:
  - description: The git repo will be cloned onto the volume backing this workspace
    mountPath: /workspace
    name: output