apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: task-integration-test
spec:
  workspaces:
    - name: shared-workspace
      description: A workspace that contains the fetched git repository.
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    name: ""
    resources: {}
  steps:
  - image: ruby:3.0.3
    name: features-tests
    resources: {}
    script: |
      #!/bin/bash
      set -e
      bundle install 
      echo "-------- RSPEC | START --------"
      bundle exec rspec spec/features
      echo "-------- RSPEC | END --------"