apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: task-unit-test
spec:
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    name: ""
    resources: {}
  steps:
  - image: ruby:3.0.3
    name: models-test # to improve these RSPEC checks should be in parallel
    resources: {}
    script: |
      #!/bin/bash
      set -e
      bundle install 
      echo "-------- RSPEC | START --------"
      bundle exec rspec spec/models
      echo "-------- RSPEC | END --------"
  - image: ruby:3.0.3
    name: controller-tests
    resources: {}
    script: |
      #!/bin/bash
      set -e
      bundle install 
      echo "-------- RSPEC | START --------"
      bundle exec rspec spec/requests
      echo "-------- RSPEC | END --------"
  workspaces:
  - description: The git repo will be cloned onto the volume backing this workspace
    mountPath: /workspace
    name: output