apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/ruby/pullrequest.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - image: ghcr.io/jenkins-x/jx-boot:3.2.256
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
            jx gitops pr variables
        - image: ghcr.io/jenkins-x/jx-registry:0.1.1
          name: check-registry
          resources: {}
        - image: ruby:3.0.3
          name: code-scanning-ruby-lint # to improve these Code Scanning steps should be in parallel
          resources: {}
          script: |
            #!/bin/bash

            set -e # Makes terminal exit on error
            apt update
            apt install nodejs -y
            node -v
            apt install npm -y

            # For Prettier - ESLint - stylelint
            npm install --save-dev prettier-eslint
            npm install --save-dev prettier-eslint-cli
            npm install prettier-stylelint --save-dev

            # Standrd Ruby on Rails bundle install
            bundle install

            echo "-------- RUBOCOP | START --------"
            cd ./bin
            chmod u+r+x error_handler.sh
            ./error_handler.sh "rubocop --parallel"; cd ..
            echo "-------- RUBOCOP | END --------"
            
            echo "-------- Prettier - ESLint - stylelint | START --------"
            cd ./bin 
            ./error_handler.sh "npm run fix-code"
            ./error_handler.sh "npm run fix-styles"
            cd ..
            echo "-------- Prettier - ESLint - stylelint | END --------"
        - image: ruby:3.0.3
          name: code-scanning-ruby-security-checks # Brakeman security test
          resources: {}
          script: |
            #!/bin/bash
            gem install brakeman
            brakeman -aq
        - image: ruby:3.0.3
          name: unit-test-models-test # to improve these RSPEC checks should be in parallel
          resources: {}
          script: |
            #!/bin/bash
            bundle install 
            bundle exec rspec spec/models
        - image: ruby:3.0.3
          name: unit-test-controller-tests
          resources: {}
          script: |
            #!/bin/bash
            bundle install 
            bundle exec rspec spec/requests
        - image: ruby:3.0.3
          name: integration-test-features-tests
          resources: {}
          script: |
            #!/bin/bash
            bundle install 
            bundle exec rspec spec/features
        - image: gcr.io/kaniko-project/executor:v1.6.0-debug
          name: build-container-build
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=${DOCKERFILE_PATH:-Dockerfile} --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
        - image: ghcr.io/jenkins-x-plugins/jx-preview:0.0.192
          name: promote-jx-preview
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            jx preview create
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
